version: '3.8'

services:
  go-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-dev
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    networks:
      - app-network
    tty: true
    stdin_open: true

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: